[package]
name = "gpuidart"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
benchmark-trace = []

[dependencies]
async-channel = "2"
gpui-kit = { git = "https://github.com/longbridge/gpui-kit", rev = "21622a70efd25219d26aa459164878c4da9e39f8", features = ["profiler"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
libc = "0.2"

[dev-dependencies]
gpui-kit = { git = "https://github.com/longbridge/gpui-kit", rev = "21622a70efd25219d26aa459164878c4da9e39f8", features = ["test-support"] }
